baseURL = "https://postmeritocracy.org"
languageCode = "en-us"
title = "The Post-Meritocracy Manifesto"

buildFuture = true
enableGitInfo = true
disableHugoGeneratorInject = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-101929377-3"

[outputs]
home = ["html"]
page = ["html"]

[Languages]

[Languages.en]
languageName = "English"
languageCode = "en"
weight = 1

[Languages.sp]
languageName = "Spanish"
languageCode = "sp"

[Languages.hi]
languageName = "हिन्दी भाषा"
languageCode = "hi"

[Languages.de]
languageName = "Deutsch"
languageCode = "de"

[Languages.pt]
languageName = "Português"
languageCode = "pt"
